### PR TITLE
Responsive badge

### PR DESCRIPTION
**Pull request by gp22**
Add responsive font sizes for header badge, subtitle and buttons.
Also changed phone-only screen breakpoint to 600px to fix a problem where the buttons were not breaking properly when the screen size was set to exactly 600px.

### CODE REVIEW

**Comment by gp22** [comment]
One issue I noticed is that setting font sizes for h1 and h2 effect the badge and subtitle text properly, but have no effect on the other h2 elements on the page.

**Comment by friscomm** [comment]
Hey dude, do you think we should change the phone-only mixin range? I'm okay with it, but one thing we'll want to be aware of is if we want to do a separate layout for the tablet portrait. Since the tablet portrait starts at 600px our options to fix your problem are:

1) Change phone-only screen to 600px

2) Add the tablet-portrait-only mixin to the buttons as well, and put the same css under this mixin 

Either of these would fix the issue with the buttons breaking properly.

I'm open for either one, just wanna put this out there in case we think we'll want some tablet specific CSS because if so, that could give us some issues if we have css rules for phones that are applied at 600px and different css for tablets that start being applied at 600px as well.

So we can make the change and just fix it if we need to do tablet specific stuff, or add the tablet-portrait-only mixin to the buttons.

What're your thoughts?

**Comment by gp22** [comment]
It was only a 1px change from 599px to 600px. So when the buttons were set to `display: none;` for the phone-only size, they didn't display properly only when the screen was set to exactly 600px wide.

So it was likely nobody would ever see it.

I think the phone-only size works up to the specified resolution 600px and the tablet resolution takes over at that exact same resolution. I think having the phone-only resolution end at 599px and the tablet-portrait take over at 600px made it so that at exactly 600px the rules didn't apply properly.

So instead of adding more rules I think we could try it like this (with the phone-only at 600px), and if it causes problems change it back to 599px and add the mixin.

**Comment by friscomm** [comment]
Sounds good to me! I'll merge the pull request 👍

**Pull request merged**
